"""Ninja Harness — trace-first evals for agents that need to survive production."""

from ninja_harness.export import (
    build_example,
    compress_run,
    export_runs,
    to_messages,
    write_jsonl,
)
from ninja_harness.schemas import (
    AgentRun,
    AgentStep,
    EvaluationCase,
    EvaluationResult,
    GuardrailEvent,
    Handoff,
    MetricResult,
    RunManifest,
    RunReport,
    SuiteCaseSpec,
    SuiteResult,
    SuiteSpec,
    TaskSpec,
    ToolCall,
    ToolSpec,
    TrajectoryExample,
    TrajectoryExportSummary,
)

__version__ = "0.9.0"
__all__ = [
    "AgentRun",
    "AgentStep",
    "EvaluationCase",
    "EvaluationResult",
    "GuardrailEvent",
    "Handoff",
    "MetricResult",
    "RunManifest",
    "RunReport",
    "SuiteCaseSpec",
    "SuiteResult",
    "SuiteSpec",
    "TaskSpec",
    "ToolCall",
    "ToolSpec",
    "TrajectoryExample",
    "TrajectoryExportSummary",
    "__version__",
    "build_example",
    "compress_run",
    "export_runs",
    "to_messages",
    "write_jsonl",
]
