"""Report generation — Markdown and JSON output for evaluation results."""

from __future__ import annotations

import json

from ninja_harness.schemas import AgentRun, EvaluationResult, MetricResult, SuiteResult

_CERT_EMOJI = {"PASS": "✅", "WARN": "⚠️", "FAIL": "❌"}
_GRADE_EMOJI = {"A": "🥇", "B": "🥈", "C": "🥉", "D": "📉", "F": "💥"}


def _score_display(mr: MetricResult) -> str:
    if not mr.is_applicable:
        return "N/A"
    return f"{mr.score:.3f}"


def _status_display(mr: MetricResult) -> str:
    if not mr.is_applicable:
        return "SKIP"
    return "PASS" if mr.passed else "FAIL"


def _key_finding(mr: MetricResult) -> str:
    if not mr.is_applicable:
        return mr.details.get("reason", "Not applicable")
    if mr.failure_reasons:
        return mr.failure_reasons[0][:80]
    if mr.passed:
        return "No issues detected"
    return "See details"


def generate_markdown_report(
    result: EvaluationResult,
    run: AgentRun | None = None,
) -> str:
    cert_sym = _CERT_EMOJI.get(result.certification, "")
    grade_sym = _GRADE_EMOJI.get(result.grade, "")

    lines: list[str] = [
        "# Ninja Harness Evaluation Report",
        "",
        "## Summary",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Run ID | `{result.run_id}` |",
    ]

    if run:
        lines += [
            f"| Agent | {run.agent_name} |",
            f"| Task | {run.task[:80]} |",
        ]

    if result.case_id:
        lines.append(f"| Case ID | `{result.case_id}` |")

    lines += [
        f"| Ninja Score | **{result.ninja_score:.1f} / 100** |",
        f"| Grade | **{grade_sym} {result.grade}** |",
        f"| Certification | **{cert_sym} {result.certification}** |",
        "",
        "## Metric Breakdown",
        "",
        "| Metric | Score | Status | Key Finding |",
        "|---|---:|---|---|",
    ]

    for mr in result.metric_results:
        lines.append(
            f"| {mr.name.replace('_', ' ').title()} "
            f"| {_score_display(mr)} "
            f"| {_status_display(mr)} "
            f"| {_key_finding(mr)} |"
        )

    lines += ["", "## Trace Findings", ""]

    if result.top_failure_reasons:
        lines.append("### Failure Points")
        for reason in result.top_failure_reasons:
            lines.append(f"- {reason}")
        lines.append("")

    if result.recommended_fixes:
        lines.append("### Suggested Fixes")
        for fix in result.recommended_fixes:
            lines.append(f"- {fix}")
        lines.append("")

    lines += [
        "## Safety Notes",
        "",
        "> **Defensive use only.** Red-team findings identify risky patterns in traces.",
        "> Human review is required before deployment in high-risk domains.",
        "> A passing safety score is not a substitute for a full security review.",
        "",
        "---",
        "",
        "_Generated by [Ninja Harness](https://github.com/gagans23/ninja-harness)_",
        "",
    ]

    return "\n".join(lines)


def generate_json_report(result: EvaluationResult) -> str:
    return result.model_dump_json(indent=2)


def generate_suite_markdown_report(suite: SuiteResult) -> str:
    lines: list[str] = [
        f"# Ninja Harness Suite Report — {suite.name}",
        "",
        "## Summary",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Total cases | {suite.total} |",
        f"| Passed | {suite.passed} |",
        f"| Warned | {suite.warned} |",
        f"| Failed | {suite.failed} |",
        f"| Errors | {len(suite.errors)} |",
        f"| Pass rate | {suite.pass_rate:.0%} |",
        f"| Average score | {suite.average_score:.1f} / 100 |",
        "",
        "## Cases",
        "",
        "| Run ID | Score | Grade | Certification |",
        "|---|---:|---|---|",
    ]
    for r in suite.results:
        sym = _CERT_EMOJI.get(r.certification, "")
        lines.append(
            f"| `{r.run_id}` | {r.ninja_score:.1f} | {r.grade} | {sym} {r.certification} |"
        )

    if suite.errors:
        lines += ["", "## Errors", ""]
        for e in suite.errors:
            lines.append(f"- `{e.get('trace')}` — {e.get('error')}")

    lines += [
        "",
        "---",
        "",
        "_Generated by [Ninja Harness](https://github.com/gagans23/ninja-harness)_",
        "",
    ]
    return "\n".join(lines)


def generate_suite_json_report(suite: SuiteResult) -> str:
    return suite.model_dump_json(indent=2)


def save_report(content: str, path: str) -> None:
    with open(path, "w") as f:
        f.write(content)


def results_to_dict(result: EvaluationResult) -> dict:
    return json.loads(result.model_dump_json())
